# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"


# HTML Title
title: "COSCUP's Links"

# Avatar image path
avatar: "./images/profile.png"

# Name section text
name: "@COSCUP"

# Tagline section text
tagline: |-
    COSCUP is an annual conference for open source enthusiasts, organized by the community since 2006.
    We're happy to announce that this year, we are co-hosting it with UbuCon Asia.
    Join us in Taipei on August 8–9, 2026 — see you there!

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa fa-bullhorn"
      text: "2026 Call for Papers"
      url: "https://pretalx.coscup.org/coscup-2026/cfp"
      alt: "COSCUP's CFP"
      title: "COSCUP's CFP"
      target: "_blank"
  - link:
      icon: "fa fa-desktop"
      text: "COSCUP's Website"
      url: "https://coscup.org/2025/en/"
      alt: "COSCUP's 2025 Website"
      title: "COSCUP's 2025 Website"
      target: "_blank"
  - link:
      icon: "fa fa-heart-o"
      text: "Want to hear more about COSCUP?"
      url: "https://app.formbricks.com/s/cmkhqoplq4g5kad01ix19rh6q"
      alt: "COSCUP's form"
      title: "COSCUP's form"
      target: "_blank"



# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-mastodon"
      url: "https://floss.social/@COSCUP"
      title: "COSCUP's Mastodon"
      alt: "COSCUP's MastOdon"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/COSCUP"
      title: "COSCUP's GitHub"
      alt: "COSCUP's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-square-x-twitter"
      url: "https://x.com/coscup"
      title: "COSCUP's x"
      alt: "COSCUP's x"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/company/coscup-tw/"
      title: "COSCUP's LinkedIn"
      alt: "COSCUP's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:program@coscup.org"
      title: "Email: program@coscup.org"
      alt: "program@coscup.org"
      target: "_blank"

# Footer text
footer: >
    Hi there! Please follow us or contact us through the platforms above.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2026 Powered by <a href="https://github.com/Melaniecode/coscup.bio" target="_blank">COSCUP</a>
